### PR TITLE
Update helpline.json

### PR DESCRIPTION
**Pull request by GaelKBertrand**

### CODE REVIEW

**Comment by GaelKBertrand** [comment]
I was rushing. You aren't  bothered to continue to work on this bot?

**Comment by GaelKBertrand** [comment]
Are you still a student/sg? I saw the guy keeps sending you weekly dining menu

**Comment by adiwajshing** [comment]
No, I'm an RA -- Mr. Mridul sends the menu every week so that Messcat has all the latest info. There's a CI flow that automatically parses & updates the menu.

**Comment by GaelKBertrand** [comment]
Sounds good. Then we just needs updates in 'helpline' only

**Pull request merged**
